### ISSUE TITLE
Compatibility with Android 12

### ISSUE THREAD

**Issue by Newsid** [taku-ka/SalesforceMarketingCloudSDKXamarin#1]
Hello,
In a project I'm working on we need to update the marketing cloud sdk to an 8.x version, that provides the mandatory compatibility for Android 12.

I tried to substitute the marketing cloud aar with the version 8.0.6 in the binding library but I'm facing some parsing issues that prevents the binding library to build.

There is any chance that you already solved this issue?

Thank you in advance

**Comment by hafeelpurakkattu** [comment]
I am also facing the same issue. @taku-ka  Are you planning to support marketing cloud sdk  8.x version?

@Newsid Did you find any solution?

**Comment by Remonell** [comment]
I also would love a solution to this problem. @hafeelpurakkattu Any updates?

**Comment by taku-ka** [comment]
Please use this version 7.4.4 

https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/repository/com/salesforce/marketingcloud/marketingcloudsdk/7.4.4/
