### ISSUE TITLE
iOS connection Not-opted-in

### ISSUE THREAD

**Issue by alvaroibna** [taku-ka/SalesforceMarketingCloudSDKXamarin#2]
Hi @taku-ka, thans in advance for your code.
We've implemented your solution in Xamarin for iOS but we are facing the problem that in SF the connection is not opening as we expect: they receive the status not-opted-in and they can't communicate with our APP. 
We are thinking about a paid collab with you because we really need this solution and we would like to implement something like your solution. Please contact me by e-mail (alvaroibna@gmail.com) if you are interested or if you have some ideas.
Thanks!

**Comment by taku-ka** [comment]
Email send
