### ISSUE TITLE
Paid Collab Opportunity.

### ISSUE THREAD

**Issue by luqmannor** [taku-ka/SalesforceMarketingCloudSDKXamarin#4]
Hi @taku-ka,

This is the only SDK that we can find for Xamarin implementation for Marketing Cloud and I would say this is the best shot that our company have to land a project with a client.

We are trying to implement this SDK for IOS and Android but we need guidance and support for this SDK. We would like to invite you for a paid collab with us for this project.

Please contact me by e-mail ([luqman@telcowin.com](mailto:luqman@telcowin.com)) if you are interested.

**Comment by taku-ka** [comment]
Email send
